[global]
log_level = 'info'

[mode]

[mode.clients]
enabled = true
refresh = true
misbehaviour = true

[mode.connections]
enabled = true

[mode.channels]
enabled = true

[mode.packets]
enabled = true
clear_interval = 100
clear_on_start = true
tx_confirmation = true

[telemetry]
enabled = true
host = '0.0.0.0'
port = 3001

[[chains]]
id = 'onomy-mainnet-1'
rpc_addr = 'http://rpc.mainnet.onomy.io'
grpc_addr = 'http://grpc.mainnet.onomy.io'
event_source = { mode = 'push', url = 'ws://rpc.mainnet.onomy.io/websocket', batch_delay = '500ms' }
rpc_timeout = '15s'
account_prefix = 'onomy'
key_name = 'onomy-mainnet-1'
store_prefix = 'ibc'
gas_price = { price = 0, denom = 'anom' }
max_gas = 10000000
clock_drift = '5s'
trusting_period = '7days'
trust_threshold = { numerator = '1', denominator = '3' }
[chains.packet_filter]
policy = 'allow'
list = [
   ['transfer', 'channel-0'], # osmosis-1
]

[[chains]]
id = 'osmosis-1'
rpc_addr = 'https://rpc.osmosis.zone'
grpc_addr = 'https://grpc.osmosis.zone'
event_source = { mode = 'push', url = 'wss://rpc.osmosis.zone/websocket', batch_delay = '500ms' }
rpc_timeout = '15s'
account_prefix = 'osmo'
key_name = 'osmosis-1'
store_prefix = 'ibc'
gas_price = { price = 0.025, denom = 'uosmo' }
max_gas = 10000000
clock_drift = '5s'
trusting_period = '7days'
trust_threshold = { numerator = '1', denominator = '3' }
[chains.packet_filter]
policy = 'allow'
list = [
   ['transfer', 'channel-525'], # onomy-mainnet-1
]
